<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search">
    <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </label>
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <?php echo $block->getChildHtml() ?>
                </div>
            </div>
            <div class="control" id="idautosuggest" style="background-color: white;max-height:500px;z-index: 9999;overflow-y: scroll;word-wrap: break-word;position:absolute;" >
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script>
require(['jquery'],function($){
    var currentRequest = null;                                         
    $('#search').on('keyup',function(){
        <?php $loadImg = $block->getViewFileUrl('Sourabh_Autocomplete::images/rotate.gif'); ?>
        $('#idautosuggest').html("<img width='50%' height='50%' style = 'float:left;margin-left:35%;' src=<?php echo $loadImg; ?> />");
        $('#search_autocomplete').css('display','none');
        currentRequest = $.ajax({
            url: "<?php echo $this->getUrl('souautocomplete/autocomplete/index'); ?>",
            method: "POST",
            async: true,
            data: {searchterm:$('#search').val()},
            beforeSend : function(){           
                if(currentRequest != null) {
                    $('#search_autocomplete').css('display','block');
                    currentRequest.abort();
                }
            },
            success: function(response){
                doSearch = true;
                $('#idautosuggest').empty().html(response);
            },
            fail: function(response){     
            }
        });
    });
});
</script>
